spring.application.name=Interview-GO_Backend


## 구글 챗모델
# API 키 입력
spring.ai.google.genai.api-key=GOOGLE_API_KEY

# AI의 창의성 설정
spring.ai.google.genai.chat.options.temperature=0.7

# AI 모델 설정
spring.ai.google.genai.chat.options.model=gemini-2.0-flash-lite

# 최대 출력 토큰 제한
spring.ai.google.genai.chat.options.max-output-tokens=128


## 구글 TTS
# API 키 JSON (커스텀 데이터라 노란색 밑줄뜸)
google.cloud.credentials.location=TTS_API_JSON_PATH